name: "OLX Notifier"
description: "Monitora anúncios na OLX para múltiplas buscas e notifica via ntfy.sh."
version: "2.1.0"
slug: "olx-notifier"
init: false
stdin: true
arch:
  - aarch64
  - amd64

options:
  ntfy_server: https://ntfy.sh
  queries:
    - search_query: xbox series s
      enabled: true
      scope: bh_and_brazil
      ntfy_topic_bh: xbox-90
      ntfy_topic_br: xbox-90-br
      check_interval_minutes: 15
      price_min: 1000
      price_max: 1900
      blocked_keywords:
        - defeito
        - xbox one
        - desbloqueado


schema:
  ntfy_server: str
  queries:
    - search_query: str
      enabled: bool
      scope: list(bh_only|bh_and_brazil)
      ntfy_topic_bh: str
      ntfy_topic_br: str
      check_interval_minutes: int
      price_min: int?
      price_max: int?
      blocked_keywords:
        - str

map:
  - data
